config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :content, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }

  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end

  def current_user?(user)
    current_user.id == user.id
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  # include SessionsHelper

  def authenticate_user
    @current_user = User.find_by(id: session[:user_id])
    if @current_user.nil?
      flash[:notice] = "ログインが必要です。"
      redirect_to new_session_path
    end
  end

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.order(id: "DESC")
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    current_user = User.find_by(id: session[:user_id])
    @blog = current_user.blogs.build(blog_params)

    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "Blog was successfully created."
      else
        render :new
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "'Blog was successfully updated.'"
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    current_user = User.find_by(id: session[:user_id])
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  private
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:notice] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render:new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
     if action_name == 'new' || action_name == 'create'
       confirm_blogs_path
     elsif action_name == 'edit'
       blog_path
     end
   end
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

        <ul>
          <% blog.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :title %></p>
    <p><%= form.text_field :title %></p>
  </div>

  <div class="field">
    <p><%= form.label :content %></p>
    <p><%= form.text_area :content %></p>
  </div>

  <div class="field">
    <p><%= form.label :image %></p>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <p><%= form.file_field :image %></p>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <br>
  <div class="container" id="main_layout">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h3>確認画面</h3>
        <%= form.hidden_field :title %>
        <%= form.hidden_field :content %>
        <p>title:<%= @blog.title %></p>
        <p>content:<%= @blog.content %></p>
        <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
        <%= form.hidden_field :image_cache %>
        <%= form.submit "投稿する" %>
        <% end %>
        <%= form_with(model:@blog, url:new_blog_path, local:true, method:"get") do |form| %>
        <%= form.hidden_field :image_cache %>
        <%= form.submit "戻る", name: "back" %>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<br>
<div class="container" id="main_layout">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Blog</h1>

      <%= render 'form', blog: @blog %>

      <%= link_to 'Show', @blog %> |
      <%= link_to 'Back', blogs_path %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<br>
<br>
<div class="main">
 <div class="main-logo">
   Blogs
   <button type="button" class="btn btn-default"><%= link_to 'New Blog', new_blog_path %></button>
 </div>
 <br>
  <div class="container">
    <div class="alt-table-responsive">
      <table class="table　table-hover" id="main_table">
        <thead>
          <tr>
            <th>User</th>
            <th>Title</th>
            <th>Content</th>
            <th>Image</th>
            <th colspan="4"></th>
          </tr>
        </thead>

        <tbody>
          <% @blogs.each do |blog| %>
            <tr>
              <td class="col-ms-1 col-md-1"><%= blog.user.name %></td>
              <td class="col-ms-2 col-md-2"><%= blog.title %></td>
              <td class="col-ms-5 col-md-5"><%= blog.content %></td>
              <td class="col-ms-1 col-md-1"><%= image_tag blog.image.url %></td>
              <td class="col-ms-1 col-md-1"><%= link_to 'Show', blog %></td>
              <% if current_user.id == blog.user_id %>
                <td class="col-ms-1 col-md-1"><%= link_to 'Edit', edit_blog_path(blog), data: { confirm: '本当に編集しますか？' } %></td>
                <td class="col-ms-1 col-md-1"><%= link_to 'Destroy', blog, method: :delete, data: { confirm: '本当に削除しますか？?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<br>
</div>
<br>
<br>

app/views/blogs/new.html.erb
<br>
<div class="container" id="main_layout">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>New Blog</h3>

        <%= render 'form', blog: @blog %>

        <%= link_to 'Back', blogs_path %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<br>
<br>
<div class="container" id="main_layout">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p><strong>Title:</strong><%= @blog.title %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p><strong>Content:</strong><%= @blog.content %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p><strong>Image:</strong><%= image_tag @blog.image.url %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p><strong>User:</strong><%= @blog.user.name %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to 'Edit', edit_blog_path(@blog) %> |
      <%= link_to 'Back', blogs_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceBookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <div calss="header_layout">
        <!-- <p class="logo">FaceBookClone</p> -->
        <h3><span class="label label-default logo"　id="logo-link"><%= link_to "FaceBookClone", new_session_path %></span></h3>
        <p class="header_menu">
          <% if logged_in? %>
            <%= link_to "Profile", user_path(current_user.id) %>
            <%= link_to "Blog List", blogs_path(current_user.id) %>
            <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_path %>
            <%= link_to "Login", new_session_path %>
          <% end %>
        </p>
        <p id="notice"><%= notice %></p>
      </div>
    </header>
    <%= yield %>
    <footer class="fixed-bottom">
      <p>2020.08 Hello world!</p>
    </footer>
  </body>
</html>

app/views/users/new.html.erb
<br>
<div class="container" id="main_layout">
  <div class="row">
    <div class="col-md-3 col-md-offset-4">
      <h3>Sign up</h3>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with(model: @user, local: true) do |f| %>
      <p>
         <%= f.label :name, "Name" %>
         <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :email %>
        <%= f.email_field :email %>
      </p>
      <p>
        <%= f.label :password, "Password" %>
        <%= f.password_field :password %>
      </p>
      <p>確認のためもう一度ご入力ください。</p>
      <p>
        <%= f.label :password_confirmation, "Password" %>
        <%= f.password_field :password_confirmation %>
      </p>
      <p><%= f.submit "Sign Up!" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<br>
<div class="container" id="main_layout">
  <div class="row">
    <div class="col-md-3 col-md-offset-4">
      <h3><u><%= @user.name %></u></h3>
      <p>Email: <%= @user.email %></p>
    </div>
  </div>
</div>